# 9.9 Indizierung und Slicing 

## Indizierung und Slicing in eindimensionalen Array's

<font size="3.5">

* Eindimensionale Array's können wie Listen **indiziert** und in Bereiche **geschnitten** werden

</font>

In [1]:
import numpy as np


In [2]:
numbers = np.arange(1, 6)


In [3]:
numbers


array([1, 2, 3, 4, 5])

In [4]:
numbers[1]


2

In [5]:
numbers[2:4]


array([3, 4])

## Indizierung in zweidimensionalen Array's

<font size="3.5">

* Um ein Element in einem zweidimensionalen Array auszuwählen, geben Sie ein Tupel an, das die Zeilen- und Spaltenindizes des Elements in eckigen Klammern enthält

</font>

In [6]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])


In [7]:
grades


array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [8]:
grades[0, 1]  # row 0, column 1


96

## Auswählen einer Teilmenge von zweidimensionalen Array-Zeilen

<font size="3.5">

* Um eine einzelne Zeile auszuwählen, geben Sie nur einen Index in eckigen Klammern an

</font>

In [ ]:
grades[1]



<font size="3.5">

* Selektieren Sie mehrere aufeinanderfolgende Zeilen mit Slice-Notation

</font>

In [ ]:
grades[0:2]



<font size="3.5">

* Selektieren Sie mehrere nicht aufeinanderfolgende Zeilen mit einer **Liste von Zeilenindizes**

</font>

In [ ]:
grades[[1, 3]]


## Auswahl einer Teilmenge der Spalten eines zweidimensionalen Arrays

<font size="3.5">

* Der **Spaltenindex** kann auch ein spezifischer **Index**, ein **Slice** oder eine **Liste** sein.

</font>

In [9]:
grades


array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [10]:
grades[:, 0]


array([ 87, 100,  94, 100])

In [11]:
grades[:, 1:3]


array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [12]:
grades[:, [0, 2]]


array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

## Auswahl von Zeile und Spalte 

In [14]:
grades


array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [15]:
grades[0:2, 1:3]


array([[96, 70],
       [87, 90]])

In [ ]:
grades[1:3, 1:2]


In [ ]:
grades[1:3, 1]


<font size="3.5">

* Wir wollen 
    * von der 2. Zeile (Index 1), das erste Element (Index 0), 
    * sowie von der 4. Zeile (Index 3) das 3. Element (Index 2)

    </font>

In [13]:
grades[[1, 3], [0, 2]]


array([100,  82])