# 9.6 Array-Operatoren

<font size="3.5">

Mittels Array Operatoren können Sie einfache Anweisungen definieren, die Operationen auf ganzen Arrays durchführen. 
Sie können Arithmetik 
1. zwischen **Array-Werten** und **skalaren numerischen Werten**, sowie 
2. zwischen **Array-Werten derselben Form** durchführen.

</font>

In [1]:
import numpy as np


In [2]:
numbers = np.arange(1, 6)


In [3]:
numbers


array([1, 2, 3, 4, 5])

## Arithmetik zwischen Arrays und skalaren numerischen Werten

In [4]:
numbers * 2


array([ 2,  4,  6,  8, 10])

In [5]:
numbers ** 3


array([  1,   8,  27,  64, 125])

In [6]:
numbers  # numbers is unchanged by the arithmetic operators


array([1, 2, 3, 4, 5])

In [7]:
numbers += 10


In [8]:
numbers


array([11, 12, 13, 14, 15])

In [9]:
numbers2 = np.arange(1, 11).reshape(2, 5)


In [10]:
numbers2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
numbers2 * 3


array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])

### Broadcasting

<font size="3.5">

* Arithmetische Operationen erfordern als Operanden zwei Arrays gleicher Grösse und Form
* Wenn ein Operand ein skalarer Wert ist, dann führt NumPy eine Kalkulation auf jedem Element aus, so als ob der Skalar ein Array der gleichen Form wäre, d.h.
    * **`numbers * 2`** ist äquivalent zu **`numbers * [2, 2, 2, 2, 2]`** für ein 5-Elemente-Array
* Die Anwendung der Operation auf jedes Element wird als **Broadcasting** bezeichnet.
* Broadcasting kann für Arrays unterschiedlicher Grösse und Form angewendet werden, was einige leistungsstarke Manipulationen ermöglicht

</font>

## Arithmetische Operationen zwischen Array's

<font size="3.5">

* Operationen können zwischen Arrays gleicher Form ausgeführt werden

</font>

In [12]:
numbers3 = np.linspace(1.1, 5.5, 5)


In [13]:
numbers3


array([1.1, 2.2, 3.3, 4.4, 5.5])

In [14]:
numbers


array([11, 12, 13, 14, 15])

In [15]:
numbers * numbers3


array([12.1, 26.4, 42.9, 61.6, 82.5])

## Vergleichen von Arrays

<font size="3.5">

* Die einzelnen Werte zwischen zwei Arrays können mittels Vergleichsoperatoren verglichen werden
* Die Vergleiche werden elementweise durchgeführt
* Als Resultat wird ein Array mit Booleschen Werten `True` und `False` erzeugt, die dem Vergleichsergebnis jedes Elements entsprechen

</font>

In [16]:
numbers


array([11, 12, 13, 14, 15])

In [17]:
numbers >= 13


array([False, False,  True,  True,  True])

-----

In [18]:
numbers


array([11, 12, 13, 14, 15])

In [19]:
numbers3


array([1.1, 2.2, 3.3, 4.4, 5.5])

In [20]:
numbers3 < numbers


array([ True,  True,  True,  True,  True])

----

In [21]:
numbers4 = np.array([11, 10, 13, 10, 15])


In [22]:
numbers4


array([11, 10, 13, 10, 15])

In [23]:
numbers


array([11, 12, 13, 14, 15])

In [24]:
numbers4 == numbers


array([ True, False,  True, False,  True])

In [25]:
numbers4 < numbers


array([False,  True, False,  True, False])

---

In [26]:
numbers5 = np.arange(9, 19).reshape(2, 5)


In [27]:
numbers6 = np.full(5, 10)


In [28]:
numbers5


array([[ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18]])

In [29]:
numbers6


array([10, 10, 10, 10, 10])

In [30]:
numbers6 == numbers5


array([[False,  True, False, False, False],
       [False, False, False, False, False]])

In [31]:
numbers6 >= numbers5

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])