# 9.5 Erstellen von Arrays aus Bereichen

<font size="3.5">

NumPy bietet optimierte Methoden zum Erstellen von Array's aus Bereichen

</font>

## Ganzzahlige Bereiche mit `arange` erstellen

In [2]:
import numpy as np


In [3]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [4]:
np.arange(5, 10)


array([5, 6, 7, 8, 9])

In [5]:
np.arange(10, 1, -2)


array([10,  8,  6,  4,  2])

## Erstellen von linearen Fliesskomma-Bereichen mit `linspace` 

<font size="3.5">

* Der **Endwert ist im Array enthalten**

</font>

In [6]:
np.linspace(0.0, 1.0, num=5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Umformen eines Arrays (`reshape`)

<font size="3.5">

* Die Array-Methode **`reshape`** wandelt einen Array in eine andere Dimension um;
* Die neue Form des Arrays muss die **gleiche Anzahl Elemente** wie das Original haben.

</font>

In [7]:
np.arange(1, 21).reshape(4, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Anzeige grosser Arrays

<font size="3.5">

* Wenn ein Array mehr als 1000 Elemente enthält, lässt NumPy die mittleren Zeilen, Spalten, oder beides bei der Ausgabe weg

</font>

In [ ]:
np.arange(1001)


In [ ]:
np.arange(2000).reshape(2, 1000)


In [ ]:
np.arange(1, 1201).reshape(6, 200)


In [ ]:
np.arange(1, 1401).reshape(7, 200)
