# 9.12 Umformung und Transponierung

## `reshape` vs. `resize` 

In [2]:
import numpy as np
import random


In [ ]:
grades = np.random.randint(60, 101, 6)


In [ ]:
grades


<font size="3.5">

* Die Methode `reshape` liefert eine View des Original-Arrays mit neuen Dimensionen. Der ursprüngliche Array wird dabei nicht verändert.

</font>

In [ ]:
grades2 = grades.reshape(2, 3)
grades2


In [ ]:
grades


<font size="3.5">

* Die Methode `resize` modifiziert die Form des ursprünglichen Arrays

</font>

In [ ]:
grades.resize(3, 2)


In [ ]:
grades


## `flatten` vs. `ravel` 

<font size="3.5">

* Mit den Methoden **`flatten`** und **`ravel`** kann ein mehrdimensionales Array in eine einzige Dimension geändert werden

</font>

In [3]:
grades = np.random.randint(60, 101, 6).reshape(2, 3)


In [4]:
grades


array([[ 72,  96,  68],
       [ 89, 100,  68]])

<font size="3.5">

* Die Methode `flatten` macht eine flache Kopie (shallow copy) der ursprüglichen Array-Daten.

</font>

In [5]:
flattened = grades.flatten()


In [6]:
flattened


array([ 72,  96,  68,  89, 100,  68])

In [7]:
grades


array([[ 72,  96,  68],
       [ 89, 100,  68]])

In [8]:
flattened[0] = 100


In [9]:
flattened


array([100,  96,  68,  89, 100,  68])

In [10]:
grades


array([[ 72,  96,  68],
       [ 89, 100,  68]])

<font size="3.5">

* Die Methode `ravel` erzeugt eine View auf den Original-Array

</font>

In [11]:
raveled = grades.ravel()


In [12]:
raveled


array([ 72,  96,  68,  89, 100,  68])

In [13]:
grades


array([[ 72,  96,  68],
       [ 89, 100,  68]])

In [14]:
raveled[0] = 100


In [15]:
raveled


array([100,  96,  68,  89, 100,  68])

In [16]:
grades


array([[100,  96,  68],
       [ 89, 100,  68]])

## Transponieren, d.h. Vertauschen von Zeilen und Spalten

<font size="3.5">

Zeilen und Spalten eines Arrays können schnell **transponiert** werden. Der Array wird umgedreht, so dass die Zeilen zu den Spalten und die Spalten zu den Zeilen werden

</font>

<font size="3.5">

* Das **`T` Attribut** gibt eine transponierte View des Arrays zurück

</font>

In [ ]:
grades.T


In [ ]:
grades


## Horizontale und vertikale Stapelung (Stacking)

<font size="3.5">

Arrays können durch Hinzufügen von zusätzlichen Spalten oder Zeilen kombiniert werden. Das ist als **horizontales, bzw. vertikales Stapeln** bekannt.

</font>

In [ ]:
grades


In [ ]:
grades2 = np.zeros(6, dtype=int).reshape(2, 3)


In [ ]:
grades2


### `hstack`-Funktion

<font size="3.5">

* Die `hstack` (horizontal stack) Funktion ermöglicht es, Arrays horizontal zu kombinieren, sofern sie dieselbe Anzahl Zeilen haben. Es werden neue Spalten hinzugefügt.
* `hstack` erwartet ein Tupel mit den zu kombinierenden Arrays.

</font>

In [ ]:
np.hstack((grades, grades2))


### `vstack`-Funktion

<font size="3.5">

* Die `vstack` (vertical stack) Funktion ermöglicht es Arrays vertikal zu kombinieren, sofern sie dieselbe Anzahl Spalten haben. Es werden neue Zeilen hinzugefügt. 
* `vstack` erwartet ein Tupel mit den zu kombinierenden Arrays.

</font>

In [ ]:
np.vstack((grades, grades2))


### Die Dimensionen müssen bei Anwendung der `hstack`, bzw. `vstack` Methode übereinstimmen

In [ ]:
grades


In [ ]:
grades3 = np.ones((3, 4), dtype=int)


In [ ]:
grades3


In [ ]:
np.hstack((grades, grades3))


In [ ]:
np.vstack((grades, grades3))
