# Übung 9

In [106]:
import numpy as np

## Aufgabe 1

<font size="3.5">

Füllen Sie ein 2-mal-3-Array mit Einsen, ein 3-mal-3-Array mit Nullen und ein 2-mal-5-Array mit der Zahl Sieben.

</font>

In [107]:
ones_array = np.ones((2, 3), dtype=np.int32)
zeros_array = np.zeros((3, 3), dtype=float)
full_array = np.full((2, 5), 7)

print(ones_array)
print(zeros_array)
print(full_array)

[[1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


## Aufgabe 2
Erstellen Sie ein 2-mal-2-Array mit den Zahlen 0-3. Wenden Sie Broadcasting an, um jede der folgenden Operationen mit dem Original-Array durchzuführen:

1. Quadrieren Sie jedes Element des Arrays.

2. Fügen Sie 7 zu jedem Element des Arrays hinzu.

3. Multiplizieren Sie jedes Element des Arrays mit 2.

In [108]:
reshaped_array = np.arange(0, 4).reshape(2, 2)

print(reshaped_array)
print(reshaped_array ** 2)
print(reshaped_array + 7)
print(reshaped_array * 2)

[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


## Aufgabe 3
Erstellen Sie ein 3-mal-3-Array mit den geraden ganzen Zahlen von 2 bis und mit 18. Erstellen Sie einen zweiten 3-mal-3-Array, der die ganzen Zahlen von 9 bis 1 enthält, und multiplizieren Sie dann den ersten Array mit dem zweiten.

In [109]:
array_three_one = np.arange(2, 19, 2).reshape(3, 3)

In [110]:
array_three_two = np.arange(9, 0, -1).reshape(3, 3)

In [111]:
array_three_one * array_three_two

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

## Aufgabe 4 
Erstellen Sie ein 2-mal-3-Array mit den ersten sechs Potenzen von 2 (d.h. 2 ** 1, 2 ** 2, 2 ** 3, etc.). Verflachen Sie das Array zuerst mit der Methode `flatten`, dann mit `ravel`. Zeigen Sie in jedem Fall das Ergebnis an und zeigen Sie dann den ursprünglichen Array an, um zu zeigen, dass er nicht geändert wurde.

In [112]:
array_four = 2 ** np.arange(1, 7).reshape(2, 3)
print('start', array_four)
flattened_array = array_four.flatten()
flattened_array[0] = 999999
print('flattened', flattened_array)
print('original', array_four)
raveled_array = array_four.ravel()
raveled_array[0] = 999999
print('raveled', raveled_array)
print('original', array_four)

start [[ 2  4  8]
 [16 32 64]]
flattened [999999      4      8     16     32     64]
original [[ 2  4  8]
 [16 32 64]]
raveled [999999      4      8     16     32     64]
original [[999999      4      8]
 [    16     32     64]]


## Aufgabe 5
Erforschen Sie in der NumPy-Dokumentation die Array-Methode `astype`, die die Elemente eines Arrays in einen anderen Typ konvertiert. Verwenden Sie `linspace`  und `reshape`, um ein 2-mal-3-Array mit den Werten 1.1, 2.2, ..., 6.6 zu erstellen. Verwenden Sie dann die Methode `astype`, um den Array in ein Array mit ganzen Zahlen zu konvertieren.

In [113]:
float_array = np.linspace(1.1, 6.6, num=6).reshape(2, 3)
print(float_array)
float_array.astype(int)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


array([[1, 2, 3],
       [4, 5, 6]])

## Aufgabe 6
Erstellen Sie ein Array mit den Werten 1-15, formen Sie ihn in einen 3-mal-5-Array um und verwenden Sie dann Indexierungs- und Slicing-Techniken, um jede der folgenden Operationen durchzuführen:

1. Wählen Sie Zeile mit Index 2.

2. Wählen Sie Spalte mit Index 4.

3. Wählen Sie die Zeilen mit Index 0 und 1.

4. Wählen Sie die Spalten mit Index 2 - 4.

5. Wählen Sie das Element aus, das sich in Zeile mit Index 1 und Spalte mit Index 4 befindet.

6. Wählen Sie alle Elemente aus den Zeilen mit Index 1 und 2, die sich in den Spalten mit Index 0, 2 und 4 befinden.



In [114]:
array_six = np.arange(1, 16).reshape(3, 5)

print(array_six)
print(array_six[2])
print(array_six[:, 4])
print(array_six[[0,1]])
print(array_six[:, [2,3,4]])
print(array_six[1,4])
print(array_six[1:3, [0,2,4]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[ 5 10 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
10
[[ 6  8 10]
 [11 13 15]]


## Aufgabe 7
Erstellen Sie die zweidimensionalen Arrays
```
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
```
1. Verwenden Sie vertikales Stapeln, um den 4 x 2-Array namens array3 zu erstellen, wobei array1 auf array2 gestapelt wird.

2. Verwenden Sie horizontales Stapeln, um den 2 x 4-Array namens array4 zu erstellen, wobei array2 rechts von array1 liegt.

3. Verwenden Sie vertikales Stapeln mit zwei Kopien von array4, um ein 4 x 4-Array namens array5 zu erstellen.

4. Verwenden Sie horizontales Stapeln mit zwei Kopien von array3, um ein 4 x 4-Array namens array6 zu erstellen.



In [115]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
array3 = np.vstack((array1, array2))
print(array3)
array4 = np.hstack((array1, array2))
print(array4)
array5 = np.vstack((np.copy(array4), np.copy(array4)))
print(array5)
array6 = np.hstack((np.copy(array3), np.copy(array3)))
print(array6)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


## Aufgabe 8
Die in Python integrierten Listen- und Dictionary-Typen verfügen über Kopiermethoden, die flache Kopien erstellen. 


Verwenden Sie das folgende `dictionary`.
```
dictionary = {'Sophia': [97, 88]}
```
und zeigen Sie, dass die Kopiermethode eines `dictionary` tatsächlich eine flache Kopie erstellt. Rufen Sie dazu `copy` auf, um die flache Kopie zu erstellen, ändern Sie die im Original-`dictionary` gespeicherte Liste und zeigen Sie dann beide `dictionary`'s an, um zu zeigen, dass Sie den gleichen Inhalt haben.

Als nächstes verwenden Sie die `deepcopy`-Funktion des `copy`-Moduls, um eine tiefe Kopie des Wörterbuchs zu erstellen. Ändern Sie die im Original-`dictionary` gespeicherte Liste und zeigen Sie dann beide `dictionary`'s an, um nachzuweisen, dass jedes seine eigenen Daten hat.



In [116]:
import copy

dictionary = {'Sophia': [97, 88]}
dict_copy = copy.copy(dictionary)
dictionary['Sophia'][0] = 100
print(dict_copy)
print(dictionary)
deep_copy = copy.deepcopy(dictionary)
dictionary['Sophia'][0] = 99
print(deep_copy)
print(dictionary)

{'Sophia': [100, 88]}
{'Sophia': [100, 88]}
{'Sophia': [100, 88]}
{'Sophia': [99, 88]}
